"""Shared low-value base forms that should skip coarse-unit matching."""

DIRECT_NO_MATCH_BASEFORMS = {
    "a", "an", "the",
    "and", "or", "but", "if",
    "as", "than", "that", "which", "who", "whom", "whose",
    "is", "am", "are", "was", "were", "be", "been", "being",
    "do", "does", "did", "done", "doing",
    "have", "has", "had", "having",
    "can", "could", "may", "must",
    "not", "no", "yes",
    "he", "his", "him",
    "she", "her", "hers",
    "they", "their", "theirs", "them",
    "we", "our", "ours", "us",
    "you", "your", "yours",
    "it", "its",
    "i", "me", "my", "mine",
    "this", "these", "that", "those",
    "there", "here",
    "of", "to", "in", "on", "at", "for", "with", "from", "by",
    "up", "down", "out", "off",
    "myself", "yourself", "himself", "herself", "itself", "ourselves", "themselves",
    "please",
    "sorry",
    "thanks", "thank", "thank you",
    "bye", "goodbye",
    "hello", "hi",
    "nah", "nope",
    "ha", "haha", "hahaha",
    "yeah", "yah", "yep", "yup",
    "ok", "okay", "alright",
    "oh", "ooh", "ah", "uh", "um", "uhh", "umm", "hm", "hmm", "huh", "uh-huh",
    "wow", "whoa", "oops",
    "mm", "mmm", "mhm", "mm-hmm",
    "er", "erm",
    "hey",
}
